import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { adminRbacService, type Role } from '../services/admin-rbac.service'
import { ApiError } from '@/lib/api-client'
import { ConfirmDialog } from '@/components/feedback/ConfirmDialog'

const key = ['admin', 'rbac'] as const
export function AdminRolesPage() {
  const client = useQueryClient(); const [editing, setEditing] = useState<Role | null>(null); const [confirm, setConfirm] = useState<Role | null>(null)
  const roles = useQuery({ queryKey: [...key, 'roles'], queryFn: adminRbacService.roles }); const permissions = useQuery({ queryKey: [...key, 'permissions'], queryFn: adminRbacService.permissions })
  const save = useMutation({ mutationFn: ({ id, values }: { id: number | null; values: { name: string; description?: string; permissions: string[] } }) => adminRbacService.saveRole(id, values), onSuccess: () => { client.invalidateQueries({ queryKey: key }); setEditing(null) } })
  const remove = useMutation({ mutationFn: adminRbacService.deleteRole, onSuccess: () => { client.invalidateQueries({ queryKey: key }); setConfirm(null) } })
  const message = [roles.error, permissions.error, save.error, remove.error].find((value) => value instanceof ApiError)
  return <section><p className="text-sm font-semibold uppercase tracking-[.3em] text-emerald-600">Administration & sécurité</p><div className="mt-2 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-black">Rôles & permissions</h1><p className="mt-2 text-slate-600">Définissez les accès depuis une matrice de permissions.</p></div><button className="action" onClick={() => setEditing({ id: 0, code: '', name: '', description: '', is_system: false, permissions: [] })}>Créer un rôle</button></div>{message && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{message.message}</p>}<div className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm">{roles.isPending ? <p className="p-6">Chargement…</p> : roles.data?.roles.map((role) => <article key={role.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="font-bold">{role.name} {role.is_system && <span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">Système</span>}</h2><p className="mt-1 text-sm text-slate-500">{role.description || 'Aucune description'} · {role.permissions.length} permission(s)</p></div>{!role.is_system && <div className="flex gap-4"><button className="font-semibold text-emerald-700" onClick={() => setEditing(role)}>Modifier</button><button className="font-semibold text-red-700" onClick={() => setConfirm(role)}>Supprimer</button></div>}</article>)}</div>{editing && <RoleModal role={editing} permissionData={permissions.data?.permissions ?? []} pending={save.isPending} onClose={() => setEditing(null)} onSave={(values) => save.mutate({ id: editing.id || null, values })} />}<ConfirmDialog open={Boolean(confirm)} title="Supprimer ce rôle ?" description="Cette action est définitive. Un rôle encore attribué ne peut pas être supprimé." danger pending={remove.isPending} confirmLabel="Supprimer" onCancel={() => setConfirm(null)} onConfirm={() => confirm && remove.mutate(confirm.id)} /></section>
}

function RoleModal({ role, permissionData, pending, onClose, onSave }: { role: Role; permissionData: { code: string; label: string; category: string }[]; pending: boolean; onClose: () => void; onSave: (values: { name: string; description: string; permissions: string[] }) => void }) {
  const [name, setName] = useState(role.name); const [description, setDescription] = useState(role.description || ''); const [selected, setSelected] = useState(() => new Set(role.permissions.map((item) => item.code))); const grouped = permissionData.reduce<Record<string, typeof permissionData>>((all, item) => { (all[item.category] ??= []).push(item); return all }, {})
  const toggle = (code: string) => setSelected((current) => { const next = new Set(current); if (next.has(code)) next.delete(code); else next.add(code); return next })
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-slate-950/55 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave({ name, description, permissions: [...selected] }) }} className="mx-auto my-8 max-w-3xl rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{role.id ? 'Modifier le rôle' : 'Nouveau rôle'}</h2><p className="text-sm text-slate-500">Cochez les permissions à attribuer.</p></div><button type="button" className="text-slate-500" onClick={onClose}>Fermer</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Nom<input value={name} onChange={(event) => setName(event.target.value)} required maxLength={100} className="field" /></label><label className="text-sm font-semibold">Description<input value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} className="field" /></label></div><div className="mt-7 space-y-5">{Object.entries(grouped).map(([category, items]) => <fieldset key={category} className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 font-bold text-slate-800">{category}</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items?.map((permission) => <label key={permission.code} className="flex cursor-pointer items-center gap-2 rounded-lg p-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={selected.has(permission.code)} onChange={() => toggle(permission.code)} />{permission.label}</label>)}</div></fieldset>)}</div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 font-semibold">Annuler</button><button disabled={pending} className="action">{pending ? 'Enregistrement…' : 'Enregistrer'}</button></div></form></div>
}
