import { AlertTriangle, Banknote, CalendarDays, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Skeleton } from '@/components/feedback/Skeleton'
import { useAnalytics, useBackofficeBookings } from '../hooks/useBackoffice'

const money = new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' })
export function AdminDashboardPage() {
  const analytics = useAnalytics(); const bookings = useBackofficeBookings('?status=pending&limit=5'); const kpis = analytics.data?.kpis
  const cards = [{ label: 'Chiffre d’affaires confirmé', value: kpis ? money.format(kpis.revenue) : '—', icon: Banknote, tone: 'bg-emerald-50 text-emerald-700' }, { label: 'Réservations ce mois', value: kpis?.bookings_month ?? '—', icon: CalendarDays, tone: 'bg-blue-50 text-blue-700' }, { label: 'Taux d’annulation', value: kpis ? `${(kpis.cancellation_rate * 100).toFixed(1)} %` : '—', icon: AlertTriangle, tone: 'bg-amber-50 text-amber-700' }, { label: 'Nouveaux clients', value: kpis?.new_customers ?? '—', icon: UsersRound, tone: 'bg-violet-50 text-violet-700' }]
  const popular = kpis?.popular_circuits ?? []; const max = Math.max(1, ...popular.map((item) => Number(item.bookings)))
  return <section className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-emerald-600">Pilotage</p><h1 className="mt-2 text-3xl font-black">Vue d’ensemble</h1><p className="mt-2 text-slate-500">Suivez l’activité commerciale et les actions à traiter.</p></div><Link to="/admin/bookings" className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Traiter les réservations</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={20} /></span><p className="mt-5 text-2xl font-black">{analytics.isPending ? <Skeleton className="h-8 w-20" /> : value}</p><p className="mt-1 text-sm font-semibold text-slate-500">{label}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">Circuits populaires</h2><p className="mt-1 text-sm text-slate-500">Réservations cumulées par circuit.</p><div className="mt-6 space-y-4">{analytics.isPending ? <><Skeleton className="h-8" /><Skeleton className="h-8" /><Skeleton className="h-8" /></> : popular.length ? popular.map((item) => <div key={item.title}><div className="mb-1 flex justify-between text-sm font-bold"><span>{item.title || 'Offre supprimée'}</span><span>{item.bookings}</span></div><div className="h-2 overflow-hidden rounded bg-slate-100"><div className="h-full rounded bg-emerald-500" style={{ width: `${Number(item.bookings) / max * 100}%` }} /></div></div>) : <p className="text-sm text-slate-500">Pas encore de données.</p>}</div></section><section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h2 className="font-black">Alertes opérationnelles</h2><p className="mt-1 text-sm text-slate-500">Demandes en attente de validation.</p></div><Link className="text-sm font-bold text-emerald-700" to="/admin/bookings">Tout voir</Link></div>{bookings.isPending ? <div className="space-y-3 p-6"><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : bookings.data?.bookings.length ? bookings.data.bookings.map((booking) => <div className="border-b border-slate-100 p-5 last:border-0" key={booking.id}><b>{booking.customer_name || booking.customer_email}</b><p className="mt-1 text-sm text-slate-500">{booking.offer_title} · départ le {booking.start_date}</p></div>) : <p className="p-6 text-sm text-slate-500">Aucune demande en attente.</p>}</section></div></section>
}
