import { useEffect } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { Save } from 'lucide-react'
import type { HomeSettings } from '@/features/home/services/home.service'
import { useBackofficeActions, useHomeContent } from '../hooks/useBackoffice'

const defaults: HomeSettings = { hero: { title: 'Explorez le Monde avec Nous', subtitle: "Des circuits sur-mesure d'exception", ctaText: 'Découvrir nos circuits', ctaLink: '/circuits', bgImageUrl: null }, features: [{ icon: 'Compass', title: 'Circuits sur-mesure', description: 'Des itinéraires pensés autour de vos envies.' }, { icon: 'ShieldCheck', title: 'Voyagez sereinement', description: 'Une équipe locale attentive à chaque détail.' }, { icon: 'HeartHandshake', title: 'Expériences authentiques', description: 'Des rencontres et des adresses qui ont du sens.' }] }

export function AdminHomeContentPage() {
  const content = useHomeContent(); const actions = useBackofficeActions()
  const form = useForm<HomeSettings>({ defaultValues: defaults }); const features = useFieldArray({ control: form.control, name: 'features' })
  useEffect(() => { if (content.data) form.reset({ ...defaults, ...content.data, hero: { ...defaults.hero, ...content.data.hero }, features: Array.isArray(content.data.features) ? content.data.features : defaults.features }) }, [content.data, form])
  const submit = form.handleSubmit((values) => actions.saveHomeContent.mutate({ ...values, hero: { ...values.hero, bgImageUrl: values.hero.bgImageUrl || null } }))
  return <section className="max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.22em] text-emerald-600">Contenu du site</p><h1 className="mt-2 text-3xl font-black">Page d’accueil</h1><p className="mt-2 text-slate-500">Personnalisez le hero et les arguments affichés sur la landing page.</p>{content.isError && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">Impossible de charger la configuration.</p>}<form onSubmit={submit} className="mt-8 space-y-7"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Hero Banner</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Titre" registration={form.register('hero.title', { required: true, maxLength: 160 })} /><Field label="Texte du bouton" registration={form.register('hero.ctaText', { required: true, maxLength: 80 })} /><Field label="Sous-titre" textarea registration={form.register('hero.subtitle', { required: true, maxLength: 500 })} /><Field label="Lien CTA" registration={form.register('hero.ctaLink', { required: true })} /><Field label="Image de fond (URL ou média /uploads/)" registration={form.register('hero.bgImageUrl')} /></div><p className="mt-3 text-xs text-slate-500">Sans image valide, la landing utilise automatiquement son visuel local de secours.</p></section><section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Arguments de vente</h2><button type="button" disabled={features.fields.length >= 4} onClick={() => features.append({ icon: 'Sparkles', title: '', description: '' })} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold">Ajouter</button></div><div className="mt-5 space-y-5">{features.fields.map((feature, index) => <div key={feature.id} className="grid gap-3 rounded-2xl border border-slate-200 p-4 md:grid-cols-[140px_1fr_1.5fr_auto]"><input className="field" placeholder="Icône" {...form.register(`features.${index}.icon` as const, { required: true })} /><input className="field" placeholder="Titre" {...form.register(`features.${index}.title` as const, { required: true })} /><input className="field" placeholder="Description" {...form.register(`features.${index}.description` as const, { required: true })} /><button type="button" disabled={features.fields.length <= 3} onClick={() => features.remove(index)} className="text-sm font-bold text-red-700">Retirer</button></div>)}</div></section><button className="action flex items-center gap-2" disabled={actions.saveHomeContent.isPending}><Save size={17} />{actions.saveHomeContent.isPending ? 'Enregistrement…' : 'Enregistrer la page d’accueil'}</button>{actions.saveHomeContent.isSuccess && <p className="text-sm font-bold text-emerald-700">Page d’accueil mise à jour.</p>}</form></section>
}
function Field({ label, registration, textarea = false }: { label: string; registration: ReturnType<ReturnType<typeof useForm>['register']>; textarea?: boolean }) { return <label className="block text-sm font-bold text-slate-700">{label}{textarea ? <textarea className="field min-h-24" {...registration} /> : <input className="field" {...registration} />}</label> }
