import { useState, type FormEvent } from 'react'
import { Navigate, useParams } from 'react-router-dom'
import { catalogEntities, type CatalogEntity, type CatalogItem } from '@/features/catalog/types'
import { ApiError } from '@/lib/api-client'
import { useAdminActions, useAdminCatalog } from '../hooks/useAdmin'

type Field = { key: string; label: string; type?: 'number' | 'email' | 'textarea' | 'checkbox'; required?: boolean }
const configs: Record<CatalogEntity, { title: string; fields: Field[] }> = {
  categories: { title: 'Catégories', fields: [{ key: 'name', label: 'Nom', required: true }, { key: 'slug', label: 'Slug' }, { key: 'description', label: 'Description', type: 'textarea' }] },
  circuits: { title: 'Circuits', fields: [{ key: 'destination_id', label: 'ID destination', required: true }, { key: 'title', label: 'Titre', required: true }, { key: 'description', label: 'Description', type: 'textarea', required: true }, { key: 'price', label: 'Prix (€)', type: 'number', required: true }, { key: 'duration_days', label: 'Durée (jours)', type: 'number', required: true }, { key: 'capacity', label: 'Capacité', type: 'number', required: true }, { key: 'cover_image', label: 'Image (URL)' }, { key: 'gallery_urls', label: 'Galerie (une URL par ligne)', type: 'textarea' }, { key: 'is_active', label: 'Actif', type: 'checkbox' }] },
  hotels: { title: 'Hôtels', fields: [{ key: 'destination_id', label: 'ID destination', required: true }, { key: 'name', label: 'Nom', required: true }, { key: 'address', label: 'Adresse', required: true }, { key: 'price_per_night', label: 'Prix / nuit (€)', type: 'number', required: true }, { key: 'rating', label: 'Note / 5', type: 'number' }, { key: 'cover_image', label: 'Image (URL)' }, { key: 'is_active', label: 'Actif', type: 'checkbox' }] },
  guides: { title: 'Guides', fields: [{ key: 'name', label: 'Nom', required: true }, { key: 'email', label: 'E-mail', type: 'email', required: true }, { key: 'phone', label: 'Téléphone' }, { key: 'bio', label: 'Biographie', type: 'textarea' }, { key: 'avatar_url', label: 'Photo (URL)' }, { key: 'is_active', label: 'Actif', type: 'checkbox' }] },
}
function blank(fields: Field[]) { return Object.fromEntries(fields.map((field) => [field.key, field.type === 'checkbox' ? true : ''])) }

export function AdminCatalogPage() {
  const { entity = '' } = useParams(); const valid = catalogEntities.includes(entity as CatalogEntity); const type: CatalogEntity = valid ? entity as CatalogEntity : 'circuits'; const config = configs[type]
  const { data, isPending, error } = useAdminCatalog(type); const actions = useAdminActions(); const [editing, setEditing] = useState<CatalogItem | null>(null); const [values, setValues] = useState<Record<string, string | boolean>>(() => blank(config.fields))
  if (!valid) return <Navigate to="/admin/catalog/circuits" replace />
  const reset = () => { setEditing(null); setValues(blank(config.fields)) }; const edit = (item: CatalogItem) => { setEditing(item); setValues(Object.fromEntries(config.fields.map((field) => [field.key, field.type === 'checkbox' ? Boolean((item as Record<string, unknown>)[field.key]) : String((item as Record<string, unknown>)[field.key] ?? '')]))) }
  const submit = (event: FormEvent) => { event.preventDefault(); actions.saveCatalog.mutate({ entity: type, id: editing?.id ?? null, values }, { onSuccess: reset }) }
  const message = error instanceof ApiError ? error.message : actions.saveCatalog.error instanceof ApiError ? actions.saveCatalog.error.message : actions.deleteCatalog.error instanceof ApiError ? actions.deleteCatalog.error.message : null; const items = data?.[type] ?? []
  return <section><p className="text-sm font-semibold uppercase tracking-[.3em] text-emerald-600">Administration</p><h1 className="mt-2 text-3xl font-black">{config.title}</h1>{message && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{message}</p>}<div className="mt-8 grid gap-8 xl:grid-cols-[.85fr_1.5fr]"><form onSubmit={submit} className="space-y-4 rounded-3xl bg-white p-7 shadow-sm">{config.fields.map((field) => <AdminField key={field.key} field={field} value={values[field.key]} onChange={(value) => setValues({ ...values, [field.key]: value })} />)}<div className="flex gap-3"><button disabled={actions.saveCatalog.isPending} className="action mt-0">{editing ? 'Mettre à jour' : 'Enregistrer'}</button>{editing && <button type="button" onClick={reset} className="rounded-xl bg-slate-100 px-4 py-3 font-semibold">Annuler</button>}</div></form><div className="overflow-hidden rounded-3xl bg-white shadow-sm">{isPending && <p className="p-6">Chargement…</p>}{items.map((item) => <article key={item.id} className="flex items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="font-semibold">{item.name || item.title}</h2><p className="text-sm text-slate-500">{item.email || item.address || item.description}</p></div><div className="flex gap-3"><button onClick={() => edit(item)} className="font-semibold text-emerald-700">Modifier</button><button onClick={() => { if (confirm('Supprimer cet élément ?')) actions.deleteCatalog.mutate({ entity: type, id: item.id }) }} className="font-semibold text-red-700">Supprimer</button></div></article>)}</div></div></section>
}
function AdminField({ field, value, onChange }: { field: Field; value: string | boolean; onChange: (value: string | boolean) => void }) { if (field.type === 'checkbox') return <label className="flex gap-2 text-sm font-semibold"><input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} />{field.label}</label>; return <label className="block text-sm font-semibold">{field.label}{field.type === 'textarea' ? <textarea value={String(value)} onChange={(event) => onChange(event.target.value)} required={field.required} className="field min-h-24" /> : <input type={field.type || 'text'} value={String(value)} onChange={(event) => onChange(event.target.value)} required={field.required} className="field" />}</label> }
