import { useState, type FormEvent } from 'react'
import { ApiError } from '@/lib/api-client'
import { useAdminActions, useAdminUsers } from '../hooks/useAdmin'
import type { AdminUser } from '../services/admin.service'

export function AdminAccessPage() {
  const { data, isPending, error } = useAdminUsers(); const actions = useAdminActions(); const [email, setEmail] = useState('')
  const invite = (event: FormEvent) => { event.preventDefault(); actions.invite.mutate({ email }, { onSuccess: () => setEmail('') }) }
  const message = error instanceof ApiError ? error.message : actions.invite.error instanceof ApiError ? actions.invite.error.message : actions.updateRoles.error instanceof ApiError ? actions.updateRoles.error.message : null
  return <section><p className="text-sm font-semibold uppercase tracking-[.3em] text-emerald-600">Administration</p><h1 className="mt-2 text-3xl font-black">Utilisateurs et accès</h1>{message && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{message}</p>}<form onSubmit={invite} className="mt-8 flex max-w-xl gap-3 rounded-2xl bg-white p-4 shadow-sm"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="E-mail du collaborateur" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4" /><button disabled={actions.invite.isPending} className="rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white">Inviter un agent</button></form>{actions.invite.isSuccess && <p className="mt-4 text-emerald-700">Invitation envoyée.</p>}<div className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm">{isPending && <p className="p-6">Chargement…</p>}{data?.users.map((user) => <UserRow key={user.id} user={user} pending={actions.updateRoles.isPending} onSave={(role) => actions.updateRoles.mutate({ id: user.id, roles: [role] })} />)}</div></section>
}
function UserRow({ user, pending, onSave }: { user: AdminUser; pending: boolean; onSave: (role: string) => void }) { const [role, setRole] = useState(user.roles[0] || 'client'); return <article className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="font-semibold">{user.email}</h2><p className="text-sm text-slate-500">{user.is_verified ? 'Vérifié' : 'En attente'} · {user.is_active ? 'Actif' : 'Inactif'}</p></div><div className="flex gap-2"><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-lg border border-slate-300 p-2"><option value="client">Client</option><option value="agent">Agent</option><option value="admin">Admin</option></select><button disabled={pending} onClick={() => onSave(role)} className="rounded-lg bg-emerald-700 px-3 font-semibold text-white">Enregistrer</button></div></article> }
