import { zodResolver } from '@hookform/resolvers/zod'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { ConfirmDialog } from '@/components/feedback/ConfirmDialog'
import { Skeleton } from '@/components/feedback/Skeleton'
import { useBackofficeActions, useBackofficeResource } from '../hooks/useBackoffice'
import type { AdminRecord, BackofficeResource } from '../services/backoffice.service'

type Field = { key: string; label: string; type?: 'text' | 'textarea' | 'number' | 'date' | 'checkbox' | 'select'; options?: string[] }
const configs: Record<BackofficeResource, { title: string; intro: string; fields: Field[]; schema: z.ZodObject<Record<string, z.ZodType>> }> = {
  posts: { title: 'Publications & guides', intro: 'Créez les contenus éditoriaux visibles par vos voyageurs.', fields: [{ key: 'title', label: 'Titre' }, { key: 'slug', label: 'Slug' }, { key: 'excerpt', label: 'Introduction', type: 'textarea' }, { key: 'content', label: 'Contenu', type: 'textarea' }, { key: 'cover_image', label: 'Image de couverture (URL)' }, { key: 'status', label: 'Statut', type: 'select', options: ['draft', 'published', 'scheduled'] }, { key: 'published_at', label: 'Publication prévue', type: 'date' }], schema: z.object({ title: z.string().min(2), slug: z.string().min(2), excerpt: z.string().optional(), content: z.string().optional(), cover_image: z.string().optional(), status: z.enum(['draft', 'published', 'scheduled']), published_at: z.string().optional() }) },
  banners: { title: 'Bannières Hero', intro: 'Pilotez les campagnes et messages de la page d’accueil.', fields: [{ key: 'title', label: 'Titre' }, { key: 'subtitle', label: 'Sous-titre', type: 'textarea' }, { key: 'image_url', label: 'Image (URL)' }, { key: 'cta_label', label: 'Libellé CTA' }, { key: 'cta_url', label: 'Lien CTA' }, { key: 'display_order', label: 'Ordre', type: 'number' }, { key: 'is_active', label: 'Active', type: 'checkbox' }], schema: z.object({ title: z.string().min(2), subtitle: z.string().optional(), image_url: z.string().optional(), cta_label: z.string().optional(), cta_url: z.string().optional(), display_order: z.coerce.number().int().min(0), is_active: z.boolean() }) },
  coupons: { title: 'Codes promotionnels', intro: 'Créez et cadrez les réductions applicables aux circuits.', fields: [{ key: 'code', label: 'Code' }, { key: 'discount_type', label: 'Type', type: 'select', options: ['percent', 'fixed'] }, { key: 'discount_value', label: 'Valeur', type: 'number' }, { key: 'valid_from', label: 'Début', type: 'date' }, { key: 'valid_until', label: 'Fin', type: 'date' }, { key: 'max_uses', label: 'Utilisations max', type: 'number' }, { key: 'is_active', label: 'Actif', type: 'checkbox' }], schema: z.object({ code: z.string().min(2), discount_type: z.enum(['percent', 'fixed']), discount_value: z.coerce.number().positive(), valid_from: z.string().optional(), valid_until: z.string().optional(), max_uses: z.coerce.number().int().positive().optional(), is_active: z.boolean() }) },
  reviews: { title: 'Modération des avis', intro: 'Approuvez, refusez et répondez aux témoignages clients.', fields: [{ key: 'rating', label: 'Note / 5', type: 'number' }, { key: 'comment', label: 'Avis', type: 'textarea' }, { key: 'status', label: 'Décision', type: 'select', options: ['pending', 'approved', 'rejected'] }, { key: 'admin_response', label: 'Réponse publique', type: 'textarea' }], schema: z.object({ rating: z.coerce.number().int().min(1).max(5), comment: z.string().min(2), status: z.enum(['pending', 'approved', 'rejected']), admin_response: z.string().optional() }) },
}
function defaults(resource: BackofficeResource) { return Object.fromEntries(configs[resource].fields.map((field) => [field.key, field.type === 'checkbox' ? true : field.key === 'status' ? (resource === 'posts' ? 'draft' : resource === 'reviews' ? 'pending' : '') : field.key === 'discount_type' ? 'percent' : field.key === 'display_order' ? 0 : ''])) }

export function ResourceManager({ resource }: { resource: BackofficeResource }) {
  const config = configs[resource]; const { data, isPending } = useBackofficeResource(resource); const actions = useBackofficeActions(); const [editing, setEditing] = useState<AdminRecord | null>(null); const [deleting, setDeleting] = useState<AdminRecord | null>(null)
  const form = useForm<Record<string, unknown>>({ resolver: zodResolver(config.schema), defaultValues: defaults(resource) })
  useEffect(() => { form.reset(editing ? { ...defaults(resource), ...editing } : defaults(resource)) }, [editing, form, resource])
  const submit = form.handleSubmit((values) => actions.saveResource.mutate({ resource, id: editing?.id, values }, { onSuccess: () => { setEditing(null); form.reset(defaults(resource)) } }))
  const rows = data?.[resource] ?? []
  return <section className="space-y-6"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-emerald-600">Administration</p><h1 className="mt-2 text-3xl font-black">{config.title}</h1><p className="mt-2 text-slate-500">{config.intro}</p></div><div className="grid gap-6 xl:grid-cols-[minmax(320px,.8fr)_minmax(0,1.4fr)]"><form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">{editing ? 'Modifier' : 'Nouvel élément'}</h2>{editing && <button type="button" onClick={() => setEditing(null)} className="text-sm font-bold text-slate-500">Annuler</button>}</div><div className="space-y-4">{config.fields.map((field) => <ResourceField key={field.key} field={field} form={form} />)}</div><button disabled={actions.saveResource.isPending} className="action flex items-center gap-2"><Plus size={17} />{editing ? 'Enregistrer' : 'Créer'}</button></form><div className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5 font-black">Éléments ({rows.length})</div>{isPending ? <div className="space-y-3 p-6"><Skeleton className="h-18" /><Skeleton className="h-18" /><Skeleton className="h-18" /></div> : rows.length === 0 ? <p className="p-6 text-slate-500">Aucun élément à afficher.</p> : rows.map((row) => <article key={row.id} className="flex items-start justify-between gap-4 border-b border-slate-100 p-5 last:border-0"><div className="min-w-0"><h3 className="truncate font-bold">{String(row.title || row.code || `Avis ${row.rating}/5`)}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-500">{String(row.excerpt || row.subtitle || row.comment || row.status || '')}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{String(row.status || (row.is_active ? 'actif' : 'inactif'))}</span></div><div className="flex shrink-0 gap-2"><button aria-label="Modifier" onClick={() => setEditing(row)} className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50"><Pencil size={18} /></button><button aria-label="Supprimer" onClick={() => setDeleting(row)} className="rounded-lg p-2 text-red-700 hover:bg-red-50"><Trash2 size={18} /></button></div></article>)}</div></div><ConfirmDialog open={Boolean(deleting)} title="Supprimer cet élément ?" description="Cette action est définitive." danger confirmLabel="Supprimer" pending={actions.deleteResource.isPending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && actions.deleteResource.mutate({ resource, id: deleting.id }, { onSuccess: () => setDeleting(null) })} /></section>
}
function ResourceField({ field, form }: { field: Field; form: ReturnType<typeof useForm<Record<string, unknown>>> }) { const error = form.formState.errors[field.key]?.message as string | undefined; if (field.type === 'checkbox') return <label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" {...form.register(field.key)} />{field.label}</label>; return <label className="block text-sm font-bold text-slate-700">{field.label}{field.type === 'textarea' ? <textarea className="field min-h-28" {...form.register(field.key)} /> : field.type === 'select' ? <select className="field" {...form.register(field.key)}>{field.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input className="field" type={field.type || 'text'} {...form.register(field.key)} />}{error && <span className="mt-1 block text-xs text-red-700">{error}</span>}</label> }
