import { apiRequest } from '../api.js';
const entity = new URLSearchParams(location.search).get('entity') || 'circuits';
const configs = {
  categories: { title: 'Catégories', fields: [['name','Nom',true],['slug','Slug'],['description','Description','textarea']] },
  circuits: { title: 'Circuits', fields: [['destination_id','ID destination',true],['title','Titre',true],['description','Description','textarea'],['price','Prix (€)',true,'number'],['duration_days','Durée (jours)',true,'number'],['capacity','Capacité',true,'number'],['cover_image','Image (URL)'],['gallery_urls','Galerie (une URL par ligne)','textarea'],['is_active','Actif',false,'checkbox']] },
  hotels: { title: 'Hôtels', fields: [['destination_id','ID destination',true],['name','Nom',true],['address','Adresse',true],['price_per_night','Prix / nuit (€)',true,'number'],['rating','Note / 5',false,'number'],['cover_image','Image (URL)'],['is_active','Actif',false,'checkbox']] },
  guides: { title: 'Guides', fields: [['name','Nom',true],['email','E-mail',true,'email'],['phone','Téléphone'],['bio','Biographie','textarea'],['avatar_url','Photo (URL)'],['is_active','Actif',false,'checkbox']] }
};
if (!configs[entity]) location.replace('/admin-catalog.html?entity=circuits');
const config = configs[entity], form = document.getElementById('admin-form'); let editingId = null;
document.getElementById('admin-title').textContent = config.title;
form.innerHTML = config.fields.map(([key,label,required,type]) => `<label class="block text-sm font-semibold">${label}${type === 'checkbox' ? `<input id="f-${key}" type="checkbox" class="ml-3" checked>` : type === 'textarea' ? `<textarea id="f-${key}" ${required ? 'required' : ''} class="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3"></textarea>` : `<input id="f-${key}" type="${type || 'text'}" ${required ? 'required' : ''} class="mt-2 w-full rounded-xl border border-slate-200 p-3">`}</label>`).join('') + '<div class="flex gap-3"><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Enregistrer</button><button type="button" id="cancel-edit" class="hidden rounded-xl bg-slate-100 px-5 py-3 font-semibold">Annuler</button></div>';
form.addEventListener('submit', save); document.getElementById('cancel-edit').addEventListener('click', reset); load();
async function load() { try { const data = await apiRequest(`/admin/${entity}`); render(data[entity]); } catch (error) { fail(error.message); } }
function render(items) { const rows = document.getElementById('admin-rows'); rows.innerHTML = ''; items.forEach(item => { const row = document.createElement('tr'); row.className = 'border-t border-slate-100'; const name = item.name || item.title; const info = item.email || item.address || (item.price !== undefined ? `${Number(item.price).toFixed(2)} €` : item.description || ''); row.innerHTML = `<td class="px-5 py-4 font-semibold"></td><td class="px-5 py-4 text-slate-500"></td><td class="px-5 py-4 text-right"><button class="edit font-semibold text-blue-600">Modifier</button><button class="delete ml-3 font-semibold text-rose-600">Supprimer</button></td>`; row.children[0].textContent = name; row.children[1].textContent = info; row.querySelector('.edit').onclick = () => edit(item); row.querySelector('.delete').onclick = () => remove(item.id, name); rows.appendChild(row); }); }
function edit(item) { editingId = item.id; config.fields.forEach(([key,,,type]) => { const input = document.getElementById(`f-${key}`); input[type === 'checkbox' ? 'checked' : 'value'] = type === 'checkbox' ? Boolean(item[key]) : (item[key] ?? ''); }); document.getElementById('cancel-edit').classList.remove('hidden'); form.scrollIntoView({ behavior: 'smooth' }); }
function reset() { editingId = null; form.reset(); const active = document.getElementById('f-is_active'); if (active) active.checked = true; document.getElementById('cancel-edit').classList.add('hidden'); }
async function save(event) { event.preventDefault(); const body = {}; config.fields.forEach(([key,,,type]) => { const input = document.getElementById(`f-${key}`); body[key] = type === 'checkbox' ? input.checked : input.value; }); try { await apiRequest(`/admin/${entity}${editingId ? `/${editingId}` : ''}`, editingId ? 'PUT' : 'POST', body); reset(); load(); } catch (error) { fail(error.message); } }
async function remove(id, name) { if (!confirm(`Supprimer « ${name} » ?`)) return; try { await apiRequest(`/admin/${entity}/${id}`, 'DELETE'); load(); } catch (error) { fail(error.message); } }
function fail(message) { const box = document.getElementById('admin-error'); box.textContent = message; box.classList.remove('hidden'); }
