import { apiRequest } from '../api.js';
const type = new URLSearchParams(location.search).get('type') || 'circuits';
const labels = { circuits: ['CIRCUITS', 'Circuits touristiques'], hotels: ['HÉBERGEMENTS', 'Hôtels sélectionnés'], guides: ['ACCOMPAGNEMENT', 'Nos guides'], categories: ['CATÉGORIES', 'Explorer par catégorie'] };
if (!labels[type]) location.replace('/catalog.html?type=circuits');
document.getElementById('catalog-eyebrow').textContent = labels[type][0]; document.getElementById('catalog-title').textContent = labels[type][1];
load(); document.getElementById('catalog-search').addEventListener('submit', event => { event.preventDefault(); load(); });
async function load() { try { const data = await apiRequest(`/${type}?q=${encodeURIComponent(document.getElementById('catalog-q').value)}`); render(data[type]); } catch (error) { document.getElementById('catalog-error').textContent = error.message; document.getElementById('catalog-error').classList.remove('hidden'); } }
function render(items) { const grid = document.getElementById('catalog-grid'); grid.innerHTML = ''; if (!items.length) { grid.textContent = 'Aucun résultat pour le moment.'; return; } items.forEach(item => { const card = document.createElement('article'); card.className = 'overflow-hidden rounded-3xl bg-white shadow-sm'; const image = item.cover_image || item.avatar_url; card.innerHTML = `${image ? `<img src="${image}" class="h-48 w-full object-cover" alt="">` : '<div class="h-48 bg-slate-200"></div>'}<div class="p-6"><h2 class="text-xl font-bold">${escape(item.title || item.name)}</h2><p class="mt-2 line-clamp-3 text-sm text-slate-500">${escape(item.description || item.address || item.bio || '')}</p>${item.price !== undefined ? `<p class="mt-4 font-bold text-blue-700">${Number(item.price).toFixed(2)} €</p>` : ''}${type !== 'categories' ? `<a class="mt-5 inline-block font-semibold text-blue-600" href="/catalog-detail.html?type=${type}&id=${item.id}">Voir le détail →</a>` : ''}</div>`; grid.appendChild(card); }); }
function escape(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
