import { useEffect, useState } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { ApiError } from '@/lib/api-client'
import { useProfile, useUpdateProfile } from '../hooks/useProfile'
import { Link } from 'react-router-dom'
import { profileSchema, type ProfileValues } from '../schemas/profile.schema'
import type { Profile } from '../types'
import { Skeleton } from '@/components/feedback/Skeleton'
import { useSessionStore } from '@/features/auth/store/session.store'

export function ProfilePage() {
  const { data: profile, isPending, isError } = useProfile()
  const updateProfile = useUpdateProfile()
  const [avatar, setAvatar] = useState<File | null>(null)
  const { register, handleSubmit, reset, formState: { errors } } = useForm<ProfileValues>({ resolver: zodResolver(profileSchema), defaultValues: { preferredLang: 'fr', birthdate: '', gender: '', phone: '', nationality: '', country: '', city: '', postalCode: '', address: '' } })
  useEffect(() => { if (profile) reset(profileToForm(profile)) }, [profile, reset])
  if (isPending) return <section className="max-w-4xl space-y-5 rounded-3xl bg-white p-8 shadow-sm"><Skeleton className="h-5 w-28" /><Skeleton className="h-10 w-56" /><div className="grid gap-5 md:grid-cols-2"><Skeleton className="h-20" /><Skeleton className="h-20" /><Skeleton className="h-20" /><Skeleton className="h-20" /></div></section>
  if (isError || !profile) return <p role="alert">Impossible de charger le profil.</p>
  const error = updateProfile.error instanceof ApiError ? updateProfile.error.message : updateProfile.isError ? 'Impossible d’enregistrer le profil.' : null
  const submit = (values: ProfileValues) => { const form = new FormData(); Object.entries(values).forEach(([key, value]) => form.append(key, value)); if (avatar) form.append('avatar', avatar); updateProfile.mutate(form, { onSuccess: ({ user }) => { setAvatar(null); reset(profileToForm(user)); useSessionStore.getState().showToast({ title: 'Profil mis à jour', message: 'Vos informations sont bien enregistrées.' }) } }) }
  return <section className="max-w-4xl rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[.3em] text-emerald-600">Profil</p><h1 className="mt-3 text-3xl font-black">Mon profil</h1><form onSubmit={handleSubmit(submit)} noValidate className="mt-8 grid gap-5 md:grid-cols-2"><Field label="Nom complet" error={errors.name?.message}><input {...register('name')} autoComplete="name" className="field" /></Field><Field label="E-mail" error={errors.email?.message}><input {...register('email')} type="email" autoComplete="email" className="field" /></Field><Field label="Téléphone" error={errors.phone?.message}><input {...register('phone')} type="tel" autoComplete="tel" className="field" /></Field><Field label="Date de naissance" error={errors.birthdate?.message}><input {...register('birthdate')} type="date" className="field" /></Field><Field label="Nationalité" error={errors.nationality?.message}><input {...register('nationality')} className="field" /></Field><Field label="Pays" error={errors.country?.message}><input {...register('country')} className="field" /></Field><Field label="Ville" error={errors.city?.message}><input {...register('city')} className="field" /></Field><Field label="Code postal" error={errors.postalCode?.message}><input {...register('postalCode')} className="field" /></Field><Field label="Genre" error={errors.gender?.message}><input {...register('gender')} className="field" /></Field><Field label="Langue" error={errors.preferredLang?.message}><select {...register('preferredLang')} className="field"><option value="fr">Français</option><option value="en">English</option><option value="es">Español</option></select></Field><Field label="Adresse" error={errors.address?.message}><textarea {...register('address')} className="field min-h-24" /></Field><label className="mt-5 block text-sm font-semibold">Avatar<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setAvatar(event.target.files?.[0] ?? null)} className="field" /></label><div className="md:col-span-2">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{updateProfile.isSuccess && <p role="status" className="mb-3 text-sm text-emerald-700">Profil mis à jour.</p>}<button disabled={updateProfile.isPending} className="action">{updateProfile.isPending ? 'Enregistrement…' : 'Enregistrer mes informations'}</button><Link to="/change-password" className="ml-5 inline-block font-semibold text-emerald-700">Changer mon mot de passe →</Link></div></form></section>
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold">{label}{children}{error && <span className="mt-1 block text-sm font-normal text-red-600">{error}</span>}</label> }

function profileToForm(profile: Profile): ProfileValues { return { name: profile.name, email: profile.email, phone: profile.phone ?? '', birthdate: profile.birthdate ?? '', gender: profile.gender ?? '', nationality: profile.nationality ?? '', country: profile.country ?? '', city: profile.city ?? '', postalCode: profile.postalCode ?? '', address: profile.address ?? '', preferredLang: profile.preferredLang === 'en' || profile.preferredLang === 'es' ? profile.preferredLang : 'fr' } }
